files:
  - source: /TechDoc/source/*.md
    translation: /TechDoc/%locale%/%original_file_name%

files:
  - source: /TechnicalWhitePaper.md
    translation: /%locale%/%original_file_name%
  - source: /Roadmap.md
    translation: /%locale%/%original_file_name%